apiVersion: v1
kind: Service
metadata:
  name: weather-backend-svc
  namespace: web-app-test-dev
spec:
  type: ClusterIP
  selector:
    app: weather-backend
  ports:
    - port: 5000
      targetPort: 5000