apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend
  namespace: web-app-test-dev
  labels:
    app: weather-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-frontend
  template:
    metadata:
      labels:
        app: weather-frontend
    spec:
      containers:
      - name: weather-frontend
        image: 544615250077.dkr.ecr.us-east-1.amazonaws.com/weather-app-frontend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"