apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-svc
  namespace: web-app-test-dev
spec:
  type: LoadBalancer
  selector:
    app: weather-frontend
  ports:
    - port: 80
      targetPort: 8000